# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='h_fcomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hfc_time', models.DateField(auto_created=True, auto_now=True, verbose_name='\u8bc4\u8bba\u65e5\u671f')),
                ('hfc_content', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('hfc_soft', models.IntegerField(verbose_name='\u8bc4\u8bba\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u524d\u7aef\u6587\u7ae0\u8bc4\u8bba\u8868',
            },
        ),
        migrations.CreateModel(
            name='h_frontnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_artile_title', models.CharField(max_length=100, verbose_name='\u9898\u76ee')),
                ('hf_artile_content', models.TextField(null=True, verbose_name='\u5185\u5bb9')),
                ('hf_artile_content_txt', models.TextField(null=True, verbose_name='\u5185\u5bb9')),
                ('hf_artile_time', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('hf_artile_label', models.CharField(max_length=20, null=True, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
                ('hf_artile_img', models.CharField(max_length=512, null=True, verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('write_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u524d\u7aef\u7b14\u8bb0\u6587\u7ae0\u8868',
            },
        ),
        migrations.CreateModel(
            name='h_fwebs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hfw_name', models.CharField(max_length=20, null=True, verbose_name='\u540d\u79f0')),
                ('hfw_web', models.URLField(verbose_name='\u7f51\u7ad9')),
            ],
            options={
                'verbose_name': '\u53cb\u94fe\u8868',
            },
        ),
        migrations.CreateModel(
            name='h_games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hg_time', models.DateField(auto_created=True, auto_now=True, verbose_name='\u65e5\u671f')),
                ('hg_title', models.CharField(max_length=50, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('hg_info', models.CharField(max_length=200, verbose_name='\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': 'H5\u5c0f\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='h_lifelogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_artile_time', models.DateField(auto_created=True, auto_now=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('hf_artile_title', models.CharField(max_length=100, verbose_name='\u9898\u76ee')),
                ('hf_artile_content', models.TextField(null=True, verbose_name='\u5185\u5bb9')),
                ('hf_artile_cate', models.CharField(max_length=20, verbose_name='\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u751f\u6d3b\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='h_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmb_time', models.DateField(auto_created=True, auto_now=True, verbose_name='\u65e5\u671f')),
                ('hmb_title', models.CharField(max_length=200, verbose_name='\u5185\u5bb9')),
                ('hmb_soft', models.IntegerField(verbose_name='\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u7559\u8a00\u677f',
            },
        ),
        migrations.CreateModel(
            name='h_smallnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_time', models.DateField(auto_created=True, auto_now=True, verbose_name='\u65e5\u671f')),
                ('hsn_title', models.CharField(max_length=200, verbose_name='\u5185\u5bb9')),
                ('hsn_cate', models.CharField(max_length=20, verbose_name='\u7c7b\u522b')),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u8868\u4eba')),
            ],
            options={
                'verbose_name': '\u95f2\u8a00\u788e\u8bed',
            },
        ),
        migrations.CreateModel(
            name='h_visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hv_name', models.CharField(max_length=20, null=True, verbose_name='\u6635\u79f0')),
                ('hv_email', models.CharField(max_length=20, null=True, verbose_name='\u90ae\u7bb1')),
                ('hv_web', models.URLField(verbose_name='\u7f51\u7ad9')),
            ],
            options={
                'verbose_name': '\u6e38\u5ba2\u7528\u6237\u8868',
            },
        ),
        migrations.CreateModel(
            name='hf_artile_sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_sort_name', models.CharField(max_length=100, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('hf_sort_describe', models.TextField(null=True, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u524d\u7aef\u7b14\u8bb0\u5206\u7c7b\u8868',
            },
        ),
        migrations.CreateModel(
            name='hl_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlc_time', models.DateField(auto_created=True, auto_now=True, verbose_name='\u8bc4\u8bba\u65e5\u671f')),
                ('hlc_content', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('hlc_soft', models.IntegerField(verbose_name='\u8bc4\u8bba\u7ea7\u522b')),
                ('hl_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.h_frontnotes', verbose_name='\u6587\u7ae0')),
                ('hlc_puid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u88ab\u8bc4\u8bba\u4eba')),
                ('hlc_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.h_visitors', verbose_name='\u8bc4\u8bba\u4eba')),
            ],
            options={
                'verbose_name': '\u751f\u6d3b\u65e5\u5fd7\u8bc4\u8bba\u8868',
            },
        ),
        migrations.AddField(
            model_name='h_messages',
            name='hv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.h_visitors', verbose_name='\u7559\u8a00\u4eba'),
        ),
        migrations.AddField(
            model_name='h_frontnotes',
            name='hf_artile_cate',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='myweb.hf_artile_sort'),
        ),
        migrations.AddField(
            model_name='h_fcomments',
            name='hf_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.h_frontnotes', verbose_name='\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='h_fcomments',
            name='hfc_puid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u88ab\u8bc4\u8bba\u4eba'),
        ),
        migrations.AddField(
            model_name='h_fcomments',
            name='hfc_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.h_visitors', verbose_name='\u8bc4\u8bba\u4eba'),
        ),
    ]
