# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hf_artile_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='\u6635\u79f0')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('centent', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.h_frontnotes')),
            ],
            options={
                'verbose_name': '\u524d\u7aef\u7b14\u8bb0\u8bc4\u8bba\u8868',
            },
        ),
    ]
