# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_hf_artile_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hf_artile_comments',
            old_name='centent',
            new_name='content',
        ),
    ]
