# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20170517_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='hf_artile_comments',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='hf_artile_comments',
            name='email',
            field=models.CharField(max_length=256, null=True, verbose_name='email'),
        ),
    ]
