# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20170520_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='h_smallnotes',
            old_name='hsn_title',
            new_name='hsn_content',
        ),
        migrations.AlterField(
            model_name='h_smallnotes',
            name='hsn_cate',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u7c7b\u522b'),
        ),
    ]
