# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_auto_20170521_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h_lifelogs',
            name='cate',
        ),
    ]
