# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_remove_h_lifelogs_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_frontnotes',
            name='hf_artile_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6587\u7ae0\u56fe\u7247'),
        ),
    ]
